In [1]:
#!pip install pandas
#!pip install seaborn
#!pip install openpyxl
#!pip install yfinance

In [2]:
import os
import csv
import pandas as pd
import numpy as np
from matplotlib import pyplot
import math

In [3]:

df = pd.DataFrame()
header_first = True
mode='w'

for root, dirs, files in os.walk('results'):
    for f in files: 
        if(f.startswith('Result_')):
          file_name=os.path.join(root, f)
          model = f.split('_')[1]
          nm_dataset = f.split('_')[2].split('.')[0]
          dataset = pd.read_csv(file_name, sep =';', encoding = 'latin1', decimal='.')
          dataset['model']=model
          dataset['dataset']=nm_dataset
          dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)          
          dataset.columns=['Dataset','Best Params','n_time_steps','MSE', 'RMSE', 'MAE','MAPE','sMAPE','Duration','model','dataset']
          dataset.to_csv('resume_results.csv',sep=';',mode=mode,index=False, header=header_first, decimal='.')
          header_first = False
          mode='a'

C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\2152796041.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)

In [4]:
dataset = pd.read_csv(f'resume_results.csv', sep =';', encoding = 'latin1', decimal='.')
#dataset['MAE']=round(dataset['MAE'].str.replace(',','.').astype(float),2)
#dataset['MSE']=round(dataset['MSE'].str.replace(',','.').astype(float),2)
#dataset['RMSE']=round(dataset['RMSE'].str.replace(',','.').astype(float),2)
#dataset['MAPE']=round(dataset['MAPE'].str.replace(',','.').astype(float),2)
#dataset['sMAPE']=round(dataset['sMAPE'].str.replace(',','.').astype(float),2)
#dataset['Duration']=round(dataset['Duration'].str.replace(',','.').astype(float),1)

fs=dataset.pop('dataset')
dataset.insert(1, 'dataset', fs)

fs=dataset.pop('model')
dataset.insert(1, 'model', fs)

fs=dataset.pop('Dataset')

fs=dataset.pop('Best Params')
dataset.insert(9, 'Best Params', fs)


idx = dataset.groupby(['dataset'])['sMAPE'].transform(min)==dataset['sMAPE']
dataset[idx].sort_values(['dataset']).to_csv('best_sMAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_sMAPE=dataset[idx].sort_values(['dataset'])

idx = dataset.groupby(['dataset'])['MAPE'].transform(min)==dataset['MAPE']
dataset[idx].sort_values(['dataset']).to_csv('best_MAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_MAPE=dataset[idx].sort_values(['dataset'])

ds_MAPE
#dataset[idx].sort_values(['dataset'])
#dataset[idx].query('freq=="2-Day"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_day.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="1-Hour"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_hour.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="3-Week"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_week.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="2-Day"').sort_values(['SK_PONTO','freq']).head()

C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\3946950814.py:21: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  idx = dataset.groupby(['dataset'])['sMAPE'].transform(min)==dataset['sMAPE']
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\3946950814.py:25: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  idx = dataset.groupby(['dataset'])['MAPE'].transform(min)==dataset['MAPE']

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
220,LSTM,Canadian Lynx,9,249975.780000,499.975770,263.973720,28.080055,14.08,16.314668,"LSTM (100,100,100) n_time_steps=9 epochs=200"
991,MLP,IBM Stock prices,1,10.017254,3.165005,1.096754,1.114613,0.56,4.705627,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
1016,MLP,Sunspot Numbers,1,6241.149678,79.000947,29.390993,8.660113,4.43,3.016548,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
1041,MLP,TSLA Stock prices,1,108.821953,10.431776,5.561067,2.613708,1.31,3.125646,"{'activation': 'identity', 'alpha': 0.0001, 'h..."

In [5]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
idx = dataset.groupby(['dataset','model'])['sMAPE'].transform(min)==dataset['sMAPE']
dataset[idx].sort_values(['dataset','model']).to_csv('sMAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_sMAPE=dataset[idx].sort_values(['dataset','sMAPE'])
ds_sMAPE

C:\Users\Edmilson\AppData\Local\Temp\ipykernel_13680\977927266.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  idx = dataset.groupby(['dataset','model'])['sMAPE'].transform(min)==dataset['sMAPE']

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
220,LSTM,Canadian Lynx,9,249975.780000,499.975770,263.973720,28.080055,14.08,16.314668,"LSTM (100,100,100) n_time_steps=9 epochs=200"
1144,SVR,Canadian Lynx,5,572646.403700,756.734038,483.657031,117.726776,25.13,0.115015,"{'C': 1255555, 'epsilon': 0.0001, 'gamma': 1e-..."
15,ARIMA,Canadian Lynx,15,983087.783192,991.507833,864.396764,81.986731,28.44,45.005516,"ARIMA(0,0,1)(0,0,0)[12] intercept"
970,MLP,Canadian Lynx,5,998953.315457,999.476521,804.786585,169.799660,30.62,1.141213,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
991,MLP,IBM Stock prices,1,10.017254,3.165005,1.096754,1.114613,0.56,4.705627,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
1169,SVR,IBM Stock prices,5,10.476925,3.236808,1.113096,1.139145,0.57,11.480037,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-05,..."
363,LSTM,IBM Stock prices,12,164.631900,12.830896,1.471191,2.770831,1.44,364.839854,"LSTM (100,20,60) n_time_steps=12 epochs=200"
49,ARIMA,IBM Stock prices,2,325.597948,18.044333,14.453199,12.654724,6.89,44.577834,"ARIMA(1,0,1)(0,0,0)[12] intercept"
1085,STLASL,IBM Stock prices,20,2613.495621,51.122359,36.556887,26.977317,12.71,882.570060,"STL(period=12)_ARIMA((0, 1, 0))_SVR({'C': 1255..."
1016,MLP,Sunspot Numbers,1,6241.149678,79.000947,29.390993,8.660113,4.43,3.016548,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
1190,SVR,Sunspot Numbers,1,6877.389329,82.930027,30.342006,8.688594,4.46,5.983758,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-05..."
611,LSTM,Sunspot Numbers,12,518.269170,22.765526,12.280838,inf,16.59,60.278317,"LSTM (100,100,20) n_time_steps=12 epochs=200"
67,ARIMA,Sunspot Numbers,4,4608.445322,67.885531,54.065973,inf,38.49,96.498139,"ARIMA(0,0,1)(1,0,2)[12] intercept"
1108,STLASL,Sunspot Numbers,19,304758.150623,552.049047,440.427536,73.949658,65.11,539.119995,"STL(period=12)_ARIMA((0, 1, 2))_SVR({'C': 1255..."
1041,MLP,TSLA Stock prices,1,108.821953,10.431776,5.561067,2.613708,1.31,3.125646,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
1201,SVR,TSLA Stock prices,1,108.536754,10.418097,5.368873,2.614331,1.31,1.645332,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-05, ..."
828,LSTM,TSLA Stock prices,9,129.974640,11.400642,7.348946,3.330217,1.64,152.648304,"LSTM (100,100,60) n_time_steps=9 epochs=200"
1135,STLASL,TSLA Stock prices,21,12924.713161,113.686908,60.220563,25.841200,15.46,335.102416,"STL(period=12)_ARIMA((1, 1, 0))_SVR({'C': 1255..."
100,ARIMA,TSLA Stock prices,12,13317.189870,115.400129,62.858041,26.245844,15.72,100.201298,"ARIMA(0,1,0)(1,0,0)[12] intercept"

In [6]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='ARIMA']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_ARIMA_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
49,ARIMA,IBM Stock prices,2,3.255979e+02,18.044333,14.453199,12.654724,6.89,44.577834,"ARIMA(1,0,1)(0,0,0)[12] intercept"
48,ARIMA,IBM Stock prices,1,4.374720e+02,20.915832,18.959176,15.914407,8.74,15.088876,"ARIMA(0,0,0)(0,0,0)[12] intercept"
50,ARIMA,IBM Stock prices,3,4.390000e+02,20.952327,18.988328,15.937733,8.75,23.395794,"ARIMA(0,0,0)(0,0,0)[12] intercept"
51,ARIMA,IBM Stock prices,4,4.401030e+02,20.978632,19.063822,15.958127,8.76,29.006713,"ARIMA(0,0,0)(0,0,0)[12] intercept"
52,ARIMA,IBM Stock prices,5,4.412683e+02,21.006386,19.139696,15.980337,8.78,34.675835,"ARIMA(0,0,0)(0,0,0)[12] intercept"
...,...,...,...,...,...,...,...,...,...,...
17,ARIMA,Canadian Lynx,17,3.799006e+06,1949.103811,1295.000000,100.000000,100.00,17.560457,"ARIMA(0,0,0)(0,0,0)[12]"
18,ARIMA,Canadian Lynx,18,4.511762e+06,2124.090817,1590.000000,100.000000,100.00,17.122669,"ARIMA(0,0,0)(0,0,0)[12]"
20,ARIMA,Canadian Lynx,20,7.040188e+06,2653.335322,2657.000000,100.000000,100.00,12.762892,"ARIMA(0,0,0)(0,0,0)[12]"
0,ARIMA,Canadian Lynx,0,4.635416e+06,2153.001520,1334.500000,100.000000,100.00,0.042005,"ARIMA(0,0,0)(0,0,0)[12]"
63,ARIMA,Sunspot Numbers,0,1.186770e+04,108.938965,69.800000,NaN,NaN,0.319037,"ARIMA(0,0,0)(0,0,0)[12]"

In [7]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='SVR']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_SVR_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
1169,SVR,IBM Stock prices,5,1.047692e+01,3.236808,1.113096,1.139145,0.57,11.480037,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-05,..."
1187,SVR,IBM Stock prices,23,1.159356e+01,3.404932,1.364549,1.250961,0.63,16.108521,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-06..."
1184,SVR,IBM Stock prices,20,1.502178e+01,3.875794,1.352634,1.336429,0.67,15.264341,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-06, ..."
1166,SVR,IBM Stock prices,2,1.214078e+01,3.484362,1.548097,1.330718,0.67,10.417391,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-05,..."
1188,SVR,IBM Stock prices,24,1.375338e+01,3.708556,1.873318,1.531841,0.77,16.850890,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-06..."
...,...,...,...,...,...,...,...,...,...,...
1149,SVR,Canadian Lynx,10,2.245707e+06,1498.568404,567.156232,144.347840,43.67,0.101069,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-08, ..."
1145,SVR,Canadian Lynx,6,2.613572e+06,1616.654651,682.102186,145.543444,45.41,0.114384,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-08,..."
1139,SVR,Canadian Lynx,0,2.751586e+06,1658.790626,805.127554,153.809913,47.29,3.601746,"{'C': 12550, 'epsilon': 0.1, 'gamma': 1e-05, '..."
1189,SVR,Sunspot Numbers,0,3.391931e+05,582.402830,488.001428,74.007872,70.01,16.106768,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-05..."
1200,SVR,TSLA Stock prices,0,8.385814e+04,289.582694,243.680000,92.796270,86.64,3.752980,"{'C': 12550, 'epsilon': 0.1, 'gamma': 1e-05, '..."

In [8]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='LSTM']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_LSTM_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
363,LSTM,IBM Stock prices,12,1.646319e+02,12.830896,1.471191,2.770831,1.44,364.839854,"LSTM (100,20,60) n_time_steps=12 epochs=200"
463,LSTM,IBM Stock prices,24,4.665668e+01,6.830569,3.762299,2.991962,1.49,326.035975,"LSTM (60,20,100) n_time_steps=24 epochs=200"
399,LSTM,IBM Stock prices,18,5.840593e+01,7.642377,3.674034,3.063222,1.53,220.049084,"LSTM (20,20,60) n_time_steps=18 epochs=200"
270,LSTM,IBM Stock prices,3,1.077924e+02,10.382310,2.969727,3.049213,1.54,52.996340,"LSTM (20,100,60) n_time_steps=3 epochs=200"
400,LSTM,IBM Stock prices,18,5.227573e+01,7.230196,3.973991,3.146440,1.56,232.871100,"LSTM (20,20,100) n_time_steps=18 epochs=200"
...,...,...,...,...,...,...,...,...,...,...
221,LSTM,Canadian Lynx,12,2.064584e+06,1436.866100,755.318400,71.116495,56.51,13.238878,"LSTM (20,20,20) n_time_steps=12 epochs=200"
225,LSTM,Canadian Lynx,12,1.990772e+06,1410.947000,827.885900,70.999461,58.45,15.786867,"LSTM (20,60,60) n_time_steps=12 epochs=200"
224,LSTM,Canadian Lynx,12,2.291280e+06,1513.697300,746.562100,71.783006,59.40,13.985380,"LSTM (20,60,20) n_time_steps=12 epochs=200"
227,LSTM,Canadian Lynx,12,1.913754e+06,1383.385000,760.022700,73.897302,63.17,15.314688,"LSTM (20,100,20) n_time_steps=12 epochs=200"
230,LSTM,Canadian Lynx,12,2.401809e+06,1549.777100,786.956600,76.094639,65.43,14.712751,"LSTM (60,20,20) n_time_steps=12 epochs=200"

In [9]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='MLP']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_MLP_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
991,MLP,IBM Stock prices,1,1.001725e+01,3.165005,1.096754,1.114613,0.56,4.705627,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
992,MLP,IBM Stock prices,2,1.506089e+01,3.880836,1.437324,1.371378,0.68,4.417569,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
993,MLP,IBM Stock prices,3,1.468866e+01,3.832579,1.375619,1.359132,0.68,4.905916,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
995,MLP,IBM Stock prices,5,1.929698e+01,4.392833,1.589022,1.565082,0.78,4.373532,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
994,MLP,IBM Stock prices,4,2.075879e+01,4.556181,1.745120,1.655172,0.83,4.637592,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
...,...,...,...,...,...,...,...,...,...,...
1017,MLP,Sunspot Numbers,2,3.326315e+05,576.742178,480.995464,72.985809,68.27,3.124990,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
1035,MLP,Sunspot Numbers,20,3.368206e+05,580.362510,483.294489,73.744009,69.24,2.276463,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
1033,MLP,Sunspot Numbers,18,3.410601e+05,584.003481,487.785919,74.412854,70.37,3.028111,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
1015,MLP,Sunspot Numbers,0,3.491530e+05,590.891732,498.448927,82.912565,77.26,6.176162,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
987,MLP,Canadian Lynx,22,3.556101e+06,1885.762731,1021.780703,154.192025,100.00,1.558781,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."