In [1]:
#!pip install pandas
#!pip install seaborn
#!pip install openpyxl
#!pip install yfinance

In [2]:
import os
import csv
import pandas as pd
import numpy as np
from matplotlib import pyplot
import math

In [3]:

df = pd.DataFrame()
header_first = True
mode='w'

for root, dirs, files in os.walk('results'):
    for f in files: 
        if(f.startswith('Result_')):
          file_name=os.path.join(root, f)
          model = f.split('_')[1]
          nm_dataset = f.split('_')[2].split('.')[0]
          dataset = pd.read_csv(file_name, sep =';', encoding = 'latin1', decimal='.')
          dataset['model']=model
          dataset['dataset']=nm_dataset
          dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)          
          dataset.columns=['Dataset','Best Params','n_time_steps','MSE', 'RMSE', 'MAE','MAPE','sMAPE','Duration','model','dataset']
          dataset.to_csv('resume_results.csv',sep=';',mode=mode,index=False, header=header_first, decimal='.')
          header_first = False
          mode='a'

C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)
C:\Users\Edmilson\AppData\Local\Temp\ipykernel_23152\2152796041.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  dataset['dataset'].replace(['sunspot','canadian','IBM','TSLA'],['Sunspot Numbers','Canadian Lynx','IBM Stock prices','TSLA Stock prices'],inplace=True)

In [4]:
dataset = pd.read_csv(f'resume_results.csv', sep =';', encoding = 'latin1', decimal='.')
#dataset['MAE']=round(dataset['MAE'].str.replace(',','.').astype(float),2)
#dataset['MSE']=round(dataset['MSE'].str.replace(',','.').astype(float),2)
#dataset['RMSE']=round(dataset['RMSE'].str.replace(',','.').astype(float),2)
#dataset['MAPE']=round(dataset['MAPE'].str.replace(',','.').astype(float),2)
#dataset['sMAPE']=round(dataset['sMAPE'].str.replace(',','.').astype(float),2)
#dataset['Duration']=round(dataset['Duration'].str.replace(',','.').astype(float),1)

fs=dataset.pop('dataset')
dataset.insert(1, 'dataset', fs)

fs=dataset.pop('model')
dataset.insert(1, 'model', fs)

fs=dataset.pop('Dataset')

fs=dataset.pop('Best Params')
dataset.insert(9, 'Best Params', fs)


idx = dataset.groupby(['dataset'])['sMAPE'].transform(min)==dataset['sMAPE']
dataset[idx].sort_values(['dataset']).to_csv('best_sMAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_sMAPE=dataset[idx].sort_values(['dataset'])

idx = dataset.groupby(['dataset'])['MAPE'].transform(min)==dataset['MAPE']
dataset[idx].sort_values(['dataset']).to_csv('best_MAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_MAPE=dataset[idx].sort_values(['dataset'])

ds_MAPE
#dataset[idx].sort_values(['dataset'])
#dataset[idx].query('freq=="2-Day"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_day.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="1-Hour"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_hour.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="3-Week"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_model_per_reservior_week.csv',sep=';',decimal=',', index=False)
#dataset[idx].query('freq=="2-Day"').sort_values(['SK_PONTO','freq']).head()

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
131,SVR,IBM,2,2.272397,1.507447,0.925102,0.951485,0.48,1.584178,"{'C': 125550, 'epsilon': 0.001, 'gamma': 1e-06..."
177,SVR,TSLA,14,71.402943,8.450026,6.265478,3.201600,1.60,1.676532,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-05, ..."
126,SVR,canadian,22,904374.010337,950.985810,344.825348,95.207324,33.31,0.797593,"{'C': 12550, 'epsilon': 0.1, 'gamma': 1e-07, '..."

In [5]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
idx = dataset.groupby(['dataset','model'])['sMAPE'].transform(min)==dataset['sMAPE']
dataset[idx].sort_values(['dataset','model']).to_csv('sMAPE_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds_sMAPE=dataset[idx].sort_values(['dataset','sMAPE'])
ds_sMAPE

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
130,SVR,IBM,1,2.353356e+00,1.534065,0.850310,0.964160,0.48,1.601817,"{'C': 125550, 'epsilon': 0.01, 'gamma': 1e-05,..."
131,SVR,IBM,2,2.272397e+00,1.507447,0.925102,0.951485,0.48,1.584178,"{'C': 125550, 'epsilon': 0.001, 'gamma': 1e-06..."
134,SVR,IBM,5,2.344774e+00,1.531265,0.891191,0.964102,0.48,1.457724,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-05, ..."
135,SVR,IBM,6,2.392456e+00,1.546757,0.881884,0.971369,0.48,1.584359,"{'C': 125550, 'epsilon': 0.01, 'gamma': 1e-06,..."
70,MLP,IBM,1,8.650831e+01,9.300984,8.276123,6.984947,3.64,23.286870,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
5,ARIMA,IBM,2,3.255978e+02,18.044327,14.453182,12.654717,6.89,37.827930,"ARIMA(1,0,1)(0,0,0)[12] intercept"
29,ARIMA,IBM,2,3.255979e+02,18.044333,14.453199,12.654724,6.89,44.577834,"ARIMA(1,0,1)(0,0,0)[12] intercept"
46,LSTM,IBM,0,4.516344e+02,21.251691,19.319489,16.216335,8.91,103.240686,"LSTM (8,8,8) n_time_steps=0 epochs=200"
49,LSTM,IBM,0,4.516646e+02,21.252402,19.320251,16.216972,8.91,104.816100,"LSTM (8,8,64) n_time_steps=0 epochs=200"
177,SVR,TSLA,14,7.140294e+01,8.450026,6.265478,3.201600,1.60,1.676532,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-05, ..."
98,MLP,TSLA,2,9.497687e+01,9.745608,6.895231,3.660243,1.83,17.462634,"{'activation': 'identity', 'alpha': 0.001, 'hi..."
44,ARIMA,TSLA,0,3.583671e+03,59.863768,42.286667,27.118012,10.94,0.352080,"ARIMA(0,1,0)(0,0,0)[12]"
107,SVR,canadian,3,7.269600e+05,852.619514,356.204918,111.899950,25.32,1.613586,"{'C': 1255555, 'epsilon': 0.1, 'gamma': 1e-06,..."
66,MLP,canadian,5,9.989533e+05,999.476521,804.786585,169.799660,30.62,12.148804,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
1,ARIMA,canadian,1,1.133072e+06,1064.458668,768.267843,168.439932,33.61,24.485544,"ARIMA(2,0,1)(0,0,2)[12] intercept"
45,LSTM,canadian,0,1.814454e+06,1347.016750,1214.000000,312.788670,42.21,82.684807,"LSTM (8,8,8) n_time_steps=0 epochs=500"
72,MLP,sunspot,1,6.241150e+03,79.000947,29.390993,8.660113,4.43,22.136795,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
146,SVR,sunspot,1,7.038699e+03,83.896952,31.425975,8.724112,4.50,14.609558,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-05..."

In [6]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='ARIMA']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_ARIMA_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
5,ARIMA,IBM,2,3.255978e+02,18.044327,14.453182,12.654717,6.89,37.827930,"ARIMA(1,0,1)(0,0,0)[12] intercept"
29,ARIMA,IBM,2,3.255979e+02,18.044333,14.453199,12.654724,6.89,44.577834,"ARIMA(1,0,1)(0,0,0)[12] intercept"
20,ARIMA,IBM,17,4.370103e+02,20.904791,18.853031,15.794734,8.67,96.794529,"ARIMA(0,0,1)(0,0,1)[12] intercept"
21,ARIMA,IBM,18,4.377798e+02,20.923189,18.902681,15.803895,8.68,61.138829,"ARIMA(0,0,1)(0,0,1)[12] intercept"
19,ARIMA,IBM,16,4.372087e+02,20.909536,18.827263,15.807119,8.68,274.084701,"ARIMA(0,0,0)(0,0,1)[12] intercept"
18,ARIMA,IBM,15,4.368781e+02,20.901628,18.838200,15.806500,8.68,176.022501,"ARIMA(0,0,0)(0,0,1)[12] intercept"
25,ARIMA,IBM,22,4.405659e+02,20.989662,18.916411,15.855375,8.71,709.973021,"ARIMA(0,0,1)(0,0,1)[12] intercept"
26,ARIMA,IBM,23,4.411455e+02,21.003463,18.703461,15.866834,8.71,231.150749,"ARIMA(0,0,1)(0,0,1)[12] intercept"
27,ARIMA,IBM,24,4.415677e+02,21.013513,18.603913,15.876519,8.72,115.275959,"ARIMA(0,0,1)(0,0,1)[12] intercept"
4,ARIMA,IBM,1,4.374721e+02,20.915833,18.959192,15.914407,8.74,15.583759,"ARIMA(0,0,0)(0,0,0)[12] intercept"
28,ARIMA,IBM,1,4.374720e+02,20.915832,18.959176,15.914407,8.74,15.088876,"ARIMA(0,0,0)(0,0,0)[12] intercept"
6,ARIMA,IBM,3,4.390001e+02,20.952328,18.988344,15.937734,8.75,24.949724,"ARIMA(0,0,0)(0,0,0)[12] intercept"
30,ARIMA,IBM,3,4.390000e+02,20.952327,18.988328,15.937733,8.75,23.395794,"ARIMA(0,0,0)(0,0,0)[12] intercept"
31,ARIMA,IBM,4,4.401030e+02,20.978632,19.063822,15.958127,8.76,29.006713,"ARIMA(0,0,0)(0,0,0)[12] intercept"
7,ARIMA,IBM,4,4.401031e+02,20.978633,19.063834,15.958127,8.76,33.645677,"ARIMA(0,0,0)(0,0,0)[12] intercept"
8,ARIMA,IBM,5,4.412683e+02,21.006387,19.139703,15.980338,8.78,42.275065,"ARIMA(0,0,0)(0,0,0)[12] intercept"
32,ARIMA,IBM,5,4.412683e+02,21.006386,19.139696,15.980337,8.78,34.675835,"ARIMA(0,0,0)(0,0,0)[12] intercept"
9,ARIMA,IBM,6,4.423458e+02,21.032019,19.182718,15.999849,8.79,39.045066,"ARIMA(0,0,0)(0,0,0)[12] intercept"
33,ARIMA,IBM,6,4.423458e+02,21.032018,19.182710,15.999848,8.79,28.462222,"ARIMA(0,0,0)(0,0,0)[12] intercept"
11,ARIMA,IBM,8,4.439859e+02,21.070973,19.261923,16.024809,8.80,30.423553,"ARIMA(0,0,0)(0,0,0)[12] intercept"
35,ARIMA,IBM,8,4.439859e+02,21.070972,19.261930,16.024808,8.80,41.863402,"ARIMA(0,0,0)(0,0,0)[12] intercept"
34,ARIMA,IBM,7,4.432331e+02,21.053102,19.224813,16.014051,8.80,36.749272,"ARIMA(0,0,0)(0,0,0)[12] intercept"
10,ARIMA,IBM,7,4.432332e+02,21.053103,19.224821,16.014052,8.80,36.982543,"ARIMA(0,0,0)(0,0,0)[12] intercept"
16,ARIMA,IBM,13,4.458488e+02,21.115132,19.256030,16.040514,8.81,69.377974,"ARIMA(0,0,0)(0,0,0)[12] intercept"
17,ARIMA,IBM,14,4.458232e+02,21.114527,19.224931,16.037533,8.81,73.068160,"ARIMA(0,0,0)(0,0,0)[12] intercept"
38,ARIMA,IBM,11,4.452775e+02,21.101600,19.309199,16.037398,8.81,61.887066,"ARIMA(0,0,0)(0,0,0)[12] intercept"
37,ARIMA,IBM,10,4.449717e+02,21.094352,19.308513,16.035465,8.81,65.041870,"ARIMA(0,0,0)(0,0,0)[12] intercept"
36,ARIMA,IBM,9,4.445294e+02,21.083865,19.299150,16.031139,8.81,44.581619,"ARIMA(0,0,0)(0,0,0)[12] intercept"
15,ARIMA,IBM,12,4.455987e+02,21.109209,19.282396,16.039529,8.81,56.300068,"ARIMA(0,0,0)(0,0,0)[12] intercept"
14,ARIMA,IBM,11,4.452776e+02,21.101601,19.309176,16.037399,8.81,60.608396,"ARIMA(0,0,0)(0,0,0)[12] intercept"
13,ARIMA,IBM,10,4.449717e+02,21.094353,19.308506,16.035466,8.81,50.660668,"ARIMA(0,0,0)(0,0,0)[12] intercept"
12,ARIMA,IBM,9,4.445294e+02,21.083866,19.299128,16.031140,8.81,45.270596,"ARIMA(0,0,0)(0,0,0)[12] intercept"
40,ARIMA,IBM,13,4.458488e+02,21.115131,19.256022,16.040514,8.81,63.734947,"ARIMA(0,0,0)(0,0,0)[12] intercept"
41,ARIMA,IBM,14,4.458232e+02,21.114526,19.224923,16.037533,8.81,62.267185,"ARIMA(0,0,0)(0,0,0)[12] intercept"
42,ARIMA,IBM,15,4.458669e+02,21.115561,19.194447,16.035692,8.81,62.594084,"ARIMA(0,0,0)(0,0,0)[12] intercept"
39,ARIMA,IBM,12,4.455987e+02,21.109208,19.282403,16.039529,8.81,60.106621,"ARIMA(0,0,0)(0,0,0)[12] intercept"
22,ARIMA,IBM,19,4.482799e+02,21.172621,19.234716,16.068480,8.83,90.677280,"ARIMA(0,0,0)(0,0,0)[12] intercept"
23,ARIMA,IBM,20,4.492035e+02,21.194422,19.281259,16.082442,8.84,247.055216,"ARIMA(0,0,0)(0,0,0)[12] intercept"
24,ARIMA,IBM,21,4.500386e+02,21.214112,19.327792,16.094422,8.85,199.096169,"ARIMA(0,0,0)(0,0,0)[12] intercept"
44,ARIMA,TSLA,0,3.583671e+03,59.863768,42.286667,27.118012,10.94,0.352080,"ARIMA(0,1,0)(0,0,0)[12]"
1,ARIMA,canadian,1,1.133072e+06,1064.458668,768.267843,168.439932,33.61,24.485544,"ARIMA(2,0,1)(0,0,2)[12] intercept"
2,ARIMA,canadian,2,1.649469e+06,1284.316453,1141.662921,326.472169,42.14,4.353370,"ARIMA(0,0,0)(0,0,0)[12] intercept"
0,ARIMA,canadian,0,4.635416e+06,2153.001520,1334.500000,100.000000,100.00,0.092563,"ARIMA(0,0,0)(0,0,0)[12]"
3,ARIMA,IBM,0,1.441441e+04,120.060010,119.303248,100.000000,100.00,0.430099,"ARIMA(0,0,0)(0,0,0)[12]"
43,ARIMA,sunspot,0,1.186770e+04,108.938965,69.800000,NaN,NaN,0.831069,"ARIMA(0,0,0)(0,0,0)[12]"

In [7]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='SVR']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_SVR_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
131,SVR,IBM,2,2.272397e+00,1.507447,0.925102,0.951485,0.48,1.584178,"{'C': 125550, 'epsilon': 0.001, 'gamma': 1e-06..."
130,SVR,IBM,1,2.353356e+00,1.534065,0.850310,0.964160,0.48,1.601817,"{'C': 125550, 'epsilon': 0.01, 'gamma': 1e-05,..."
134,SVR,IBM,5,2.344774e+00,1.531265,0.891191,0.964102,0.48,1.457724,"{'C': 12550, 'epsilon': 0.01, 'gamma': 1e-05, ..."
135,SVR,IBM,6,2.392456e+00,1.546757,0.881884,0.971369,0.48,1.584359,"{'C': 125550, 'epsilon': 0.01, 'gamma': 1e-06,..."
136,SVR,IBM,7,2.365162e+00,1.537908,0.973746,0.977232,0.49,1.685002,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-05,..."
...,...,...,...,...,...,...,...,...,...,...
110,SVR,canadian,6,2.613572e+06,1616.654651,682.102186,145.543444,45.41,1.060087,"{'C': 12550, 'epsilon': 0.001, 'gamma': 1e-08,..."
109,SVR,canadian,5,1.386511e+06,1177.502141,852.909627,205.963371,45.68,1.589678,"{'C': 1255555, 'epsilon': 0.0001, 'gamma': 1e-..."
104,SVR,canadian,0,2.751586e+06,1658.790626,805.127554,153.809913,47.29,13.963204,"{'C': 12550, 'epsilon': 0.1, 'gamma': 1e-05, '..."
145,SVR,sunspot,0,3.391931e+05,582.402830,488.001428,74.007872,70.01,47.789522,"{'C': 12550, 'epsilon': 0.0001, 'gamma': 1e-05..."
163,SVR,TSLA,0,3.749174e+04,193.627838,189.872333,83.884340,72.46,0.986470,"{'C': 12550, 'epsilon': 0.1, 'gamma': 1e-05, '..."

In [8]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='LSTM']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_LSTM_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
46,LSTM,IBM,0,4.516344e+02,21.251691,19.319489,16.216335,8.91,103.240686,"LSTM (8,8,8) n_time_steps=0 epochs=200"
49,LSTM,IBM,0,4.516646e+02,21.252402,19.320251,16.216972,8.91,104.816100,"LSTM (8,8,64) n_time_steps=0 epochs=200"
48,LSTM,IBM,0,4.520766e+02,21.262093,19.330635,16.225676,8.92,224.269405,"LSTM (8,8,32) n_time_steps=0 epochs=200"
47,LSTM,IBM,0,4.523904e+02,21.269471,19.338539,16.232296,8.92,94.757203,"LSTM (8,8,16) n_time_steps=0 epochs=200"
50,LSTM,IBM,0,4.523937e+02,21.269548,19.338623,16.232368,8.92,334.965133,"LSTM (8,8,100) n_time_steps=0 epochs=200"
55,LSTM,IBM,0,4.547364e+02,21.324548,19.397537,16.281736,8.95,116.747490,"LSTM (8,16,100) n_time_steps=0 epochs=200"
52,LSTM,IBM,0,4.549263e+02,21.329001,19.402306,16.285732,8.96,397.571934,"LSTM (8,16,16) n_time_steps=0 epochs=200"
51,LSTM,IBM,0,4.550676e+02,21.332313,19.405853,16.288704,8.96,351.953900,"LSTM (8,16,8) n_time_steps=0 epochs=200"
54,LSTM,IBM,0,4.550606e+02,21.332150,19.405678,16.288557,8.96,71.548881,"LSTM (8,16,64) n_time_steps=0 epochs=200"
53,LSTM,IBM,0,4.549160e+02,21.328759,19.402046,16.285515,8.96,115.458181,"LSTM (8,16,32) n_time_steps=0 epochs=200"
57,LSTM,IBM,0,4.572968e+02,21.384499,19.461731,16.335530,8.98,55.808440,"LSTM (8,32,16) n_time_steps=0 epochs=200"
56,LSTM,IBM,0,4.573236e+02,21.385127,19.462402,16.336090,8.99,57.278562,"LSTM (8,32,8) n_time_steps=0 epochs=200"
59,LSTM,IBM,0,4.573862e+02,21.386589,19.463966,16.337402,8.99,70.557132,"LSTM (8,32,64) n_time_steps=0 epochs=200"
58,LSTM,IBM,0,4.573804e+02,21.386453,19.463821,16.337280,8.99,56.946189,"LSTM (8,32,32) n_time_steps=0 epochs=200"
60,LSTM,IBM,0,4.573219e+02,21.385085,19.462357,16.336052,8.99,69.102251,"LSTM (8,32,100) n_time_steps=0 epochs=200"
45,LSTM,canadian,0,1.814454e+06,1347.016750,1214.000000,312.788670,42.21,82.684807,"LSTM (8,8,8) n_time_steps=0 epochs=500"

In [9]:
#Tabela sMAPE dos melhores resultados por Dataset e Modelo
ds = dataset[dataset['model']=='MLP']
#ida = ds['sMAPE'].transform(min)==ds['sMAPE']
ds.sort_values(['sMAPE']).to_csv('best_MLP_model_per_dataset.csv',sep=';',decimal=',', index=False)
ds.sort_values(['sMAPE'])

,model,dataset,n_time_steps,MSE,RMSE,MAE,MAPE,sMAPE,Duration,Best Params
98,MLP,TSLA,2,9.497687e+01,9.745608,6.895231,3.660243,1.83,17.462634,"{'activation': 'identity', 'alpha': 0.001, 'hi..."
99,MLP,TSLA,3,1.068957e+02,10.339038,7.389691,3.855902,1.95,15.293481,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
100,MLP,TSLA,4,1.361626e+02,11.668874,8.282828,4.453805,2.22,12.431246,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
101,MLP,TSLA,5,1.520114e+02,12.329291,8.911302,4.755342,2.37,15.426031,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
97,MLP,TSLA,1,2.225513e+02,14.918153,10.484835,5.276768,2.73,20.008987,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
102,MLP,TSLA,6,2.033976e+02,14.261754,10.311635,5.491994,2.73,12.389855,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
103,MLP,TSLA,7,2.175008e+02,14.747908,10.861445,5.774286,2.87,14.998497,"{'activation': 'identity', 'alpha': 0.001, 'hi..."
70,MLP,IBM,1,8.650831e+01,9.300984,8.276123,6.984947,3.64,23.286870,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
72,MLP,sunspot,1,6.241150e+03,79.000947,29.390993,8.660113,4.43,22.136795,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
86,MLP,sunspot,15,6.533068e+03,80.827394,35.302153,9.071363,4.70,31.776272,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
95,MLP,sunspot,24,7.002151e+03,83.678858,31.884810,9.183588,4.74,29.926336,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
90,MLP,sunspot,19,7.867804e+03,88.700644,39.775169,9.968206,4.92,9.890477,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
82,MLP,sunspot,11,9.396428e+03,96.935173,47.149839,11.207016,5.80,37.096196,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
85,MLP,sunspot,14,1.133506e+04,106.466240,53.381706,11.693250,6.09,26.796475,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
75,MLP,sunspot,4,1.210622e+04,110.028286,55.342937,12.558764,6.27,38.615546,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
76,MLP,sunspot,5,1.250030e+04,111.804757,58.379945,12.809117,6.40,27.293074,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
74,MLP,sunspot,3,1.350635e+04,116.216830,52.117381,12.862015,6.46,39.577592,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
83,MLP,sunspot,12,1.314290e+04,114.642468,54.309643,13.691452,6.52,24.274734,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
81,MLP,sunspot,10,1.245226e+04,111.589687,55.145589,12.925312,6.56,43.731987,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
79,MLP,sunspot,8,1.304296e+04,114.205767,59.871632,13.094943,6.58,22.223884,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
93,MLP,sunspot,22,1.270528e+04,112.717716,60.121534,13.094486,6.66,32.281363,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
88,MLP,sunspot,17,1.353447e+04,116.337736,60.968284,13.332425,6.79,27.355660,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
78,MLP,sunspot,7,1.466158e+04,121.085011,62.790877,13.856151,6.92,7.456227,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
87,MLP,sunspot,16,1.432984e+04,119.707298,51.623320,13.246557,7.14,36.916933,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
77,MLP,sunspot,6,1.560768e+04,124.930711,66.827759,14.439234,7.18,4.589881,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
80,MLP,sunspot,9,1.828344e+04,135.216282,64.216462,14.358491,7.78,20.256693,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
69,MLP,IBM,0,4.381762e+02,20.932658,18.968081,15.934667,8.75,33.073932,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
94,MLP,sunspot,23,2.512157e+04,158.497862,88.903850,18.648156,9.01,26.269912,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
84,MLP,sunspot,13,8.149764e+04,285.477918,222.269177,37.215724,14.74,27.389150,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
66,MLP,canadian,5,9.989533e+05,999.476521,804.786585,169.799660,30.62,12.148804,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
68,MLP,canadian,7,1.287403e+06,1134.637993,1001.167065,256.662728,35.51,19.883998,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
96,MLP,TSLA,0,1.735603e+04,131.742297,124.877602,52.781093,36.72,16.608781,"{'activation': 'identity', 'alpha': 0.0001, 'h..."
67,MLP,canadian,6,1.879639e+06,1370.999452,1247.518101,351.583283,42.41,13.982169,"{'activation': 'identity', 'alpha': 0.01, 'hid..."
64,MLP,canadian,3,2.593627e+06,1610.474115,728.500000,168.196215,46.37,14.089826,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
63,MLP,canadian,2,3.216709e+06,1793.518560,843.152547,117.156104,51.03,9.321196,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
65,MLP,canadian,4,3.243214e+06,1800.892528,854.164009,115.636642,51.38,11.682505,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
62,MLP,canadian,1,3.451189e+06,1857.737672,1108.351161,107.981863,54.14,10.692275,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
61,MLP,canadian,0,3.478460e+06,1865.063019,1118.756503,106.732682,54.54,25.692528,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
92,MLP,sunspot,21,3.237740e+05,569.011420,469.183090,72.064678,66.07,8.813344,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
73,MLP,sunspot,2,3.326315e+05,576.742178,480.995464,72.985809,68.27,35.024601,"{'activation': 'relu', 'alpha': 0.01, 'hidden_..."
91,MLP,sunspot,20,3.368206e+05,580.362510,483.294489,73.744009,69.24,12.236273,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
89,MLP,sunspot,18,3.410601e+05,584.003481,487.785919,74.412854,70.37,26.238126,"{'activation': 'relu', 'alpha': 0.0001, 'hidde..."
71,MLP,sunspot,0,3.491530e+05,590.891732,498.448927,82.912565,77.26,42.577592,"{'activation': 'identity', 'alpha': 0.0001, 'h..."

In [10]:
idx = dataset.groupby(['SK_PONTO','freq','model'])['MAPE'].transform(min)==dataset['MAPE']
dataset[idx].query('model=="SVR-MLP" and freq=="1-Hour"').sort_values(['SK_PONTO','freq']).to_csv('tables/svrmlp_best_model_per_reservior_hour.csv',sep=';',decimal=',', index=False)
dataset[idx].query('model=="SVR-MLP" and freq=="2-Day"').sort_values(['SK_PONTO','freq']).to_csv('tables/svrmlp_best_model_per_reservior_day.csv',sep=';',decimal=',', index=False)
dataset[idx].query('model=="SVR-MLP" and freq=="3-Week"').sort_values(['SK_PONTO','freq']).to_csv('tables/svrmlp_best_model_per_reservior_week.csv',sep=';',decimal=',', index=False)

KeyError: 'SK_PONTO'

In [ ]:
dataset['SVR-LSTM']=np.where(dataset['model']=='SVR-LSTM',dataset['MAPE'],999)
dataset['SVR-MLP']=np.where(dataset['model']=='SVR-MLP',dataset['MAPE'],999)
dataset['SVR']=np.where(dataset['model']=='SVR',dataset['MAPE'],999)
dataset['LSTM']=np.where(dataset['model']=='LSTM',dataset['MAPE'],999)
dataset['ARIMA1']=np.where(dataset['model']=='ARIMA1',dataset['MAPE'],999)
dataset['ARIMA2']=np.where(dataset['model']=='ARIMA2',dataset['MAPE'],999)
dataset['MLP']=np.where(dataset['model']=='MLP',dataset['MAPE'],999)

:

In [ ]:
idx = dataset.groupby(['SK_PONTO','freq','SVR-LSTM','SVR-MLP','SVR','MLP','LSTM','ARIMA1','ARIMA2'])['MAPE'].transform(min)==dataset['MAPE']
dataset[idx].query('freq=="1-Hour"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_mape_per_reservior_hour.csv',sep=';',decimal=',', index=False)
dataset[idx].query('freq=="2-Day"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_mape_per_reservior_day.csv',sep=';',decimal=',', index=False)
dataset[idx].query('freq=="3-Week"').sort_values(['SK_PONTO','freq']).to_csv('tables/best_mape_per_reservior_week.csv',sep=';',decimal=',', index=False)

:

In [ ]:
dataset2=dataset.query('freq=="1-Hour"').groupby(['SK_PONTO','freq']).min(['SVR','LSTM','ARIMA1','ARIMA2','MLP','SVR-LSTM','SVR-MLP'])
dataset2

:

In [ ]:
dataset['SVR-LSTM']=np.where(dataset['model']=='SVR-LSTM',dataset['Duration'],999)
dataset['SVR-MLP']=np.where(dataset['model']=='SVR-MLP',dataset['Duration'],999)
dataset['SVR']=np.where(dataset['model']=='SVR',dataset['Duration'],999)
dataset['LSTM']=np.where(dataset['model']=='LSTM',dataset['Duration'],999)
dataset['ARIMA1']=np.where(dataset['model']=='ARIMA1',dataset['Duration'],999)
dataset['ARIMA2']=np.where(dataset['model']=='ARIMA2',dataset['Duration'],999)
dataset['MLP']=np.where(dataset['model']=='MLP',dataset['Duration'],999)
dataset2=dataset.query('freq=="1-Hour"').groupby(['SK_PONTO','freq']).min(['SVR','LSTM','ARIMA1','ARIMA2','MLP','SVR-LSTM','SVR-MLP'])
dataset2

:

In [ ]:
idx=dataset.groupby(['SK_PONTO','model','freq','MAPE'])['MAPE'].transform(min)==dataset['MAPE']
dataset[idx].sort_values(['SK_PONTO','freq']).to_csv('results/best_model_per_reservior.csv',sep=';',decimal=',', index=False)

: